// All selectable options for the onboarding flow.

export const GENRES = [
  "Sci-Fi",
  "Fantasy",
  "Mystery",
  "Romance",
  "Thriller",
  "Horror",
  "Literary Fiction",
  "Historical Fiction",
  "Non-Fiction",
  "Biography",
  "Self-Help",
  "Poetry",
  "Graphic Novels",
  "Young Adult",
  "Classics",
  "Philosophy",
  "Science",
  "True Crime",
] as const;

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "hi", label: "Hindi" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "kn", label: "Kannada" },
  { code: "ml", label: "Malayalam" },
  { code: "bn", label: "Bengali" },
  { code: "mr", label: "Marathi" },
  { code: "gu", label: "Gujarati" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "pt", label: "Portuguese" },
  { code: "zh", label: "Mandarin" },
  { code: "ar", label: "Arabic" },
] as const;

export const COUNTRIES = [
  // Asia
  { code: "IN", label: "India", flag: "🇮🇳" },
  { code: "JP", label: "Japan", flag: "🇯🇵" },
  { code: "KR", label: "South Korea", flag: "🇰🇷" },
  { code: "CN", label: "China", flag: "🇨🇳" },
  { code: "SG", label: "Singapore", flag: "🇸🇬" },
  { code: "PH", label: "Philippines", flag: "🇵🇭" },
  { code: "ID", label: "Indonesia", flag: "🇮🇩" },
  { code: "TH", label: "Thailand", flag: "🇹🇭" },
  { code: "MY", label: "Malaysia", flag: "🇲🇾" },
  { code: "VN", label: "Vietnam", flag: "🇻🇳" },
  { code: "PK", label: "Pakistan", flag: "🇵🇰" },
  { code: "BD", label: "Bangladesh", flag: "🇧🇩" },
  // Americas
  { code: "US", label: "USA", flag: "🇺🇸" },
  { code: "CA", label: "Canada", flag: "🇨🇦" },
  { code: "MX", label: "Mexico", flag: "🇲🇽" },
  { code: "BR", label: "Brazil", flag: "🇧🇷" },
  { code: "AR", label: "Argentina", flag: "🇦🇷" },
  { code: "CO", label: "Colombia", flag: "🇨🇴" },
  { code: "CL", label: "Chile", flag: "🇨🇱" },
  // Europe
  { code: "GB", label: "UK", flag: "🇬🇧" },
  { code: "DE", label: "Germany", flag: "🇩🇪" },
  { code: "FR", label: "France", flag: "🇫🇷" },
  { code: "ES", label: "Spain", flag: "🇪🇸" },
  { code: "IT", label: "Italy", flag: "🇮🇹" },
  { code: "NL", label: "Netherlands", flag: "🇳🇱" },
  { code: "SE", label: "Sweden", flag: "🇸🇪" },
  { code: "NO", label: "Norway", flag: "🇳🇴" },
  { code: "DK", label: "Denmark", flag: "🇩🇰" },
  { code: "PL", label: "Poland", flag: "🇵🇱" },
  { code: "PT", label: "Portugal", flag: "🇵🇹" },
  { code: "CH", label: "Switzerland", flag: "🇨🇭" },
  { code: "BE", label: "Belgium", flag: "🇧🇪" },
  { code: "IE", label: "Ireland", flag: "🇮🇪" },
  { code: "RU", label: "Russia", flag: "🇷🇺" },
  { code: "UA", label: "Ukraine", flag: "🇺🇦" },
  { code: "CZ", label: "Czech Republic", flag: "🇨🇿" },
  { code: "AT", label: "Austria", flag: "🇦🇹" },
  // Africa
  { code: "NG", label: "Nigeria", flag: "🇳🇬" },
  { code: "ZA", label: "South Africa", flag: "🇿🇦" },
  { code: "KE", label: "Kenya", flag: "🇰🇪" },
  { code: "EG", label: "Egypt", flag: "🇪🇬" },
  { code: "GH", label: "Ghana", flag: "🇬🇭" },
  // Middle East
  { code: "AE", label: "UAE", flag: "🇦🇪" },
  { code: "SA", label: "Saudi Arabia", flag: "🇸🇦" },
  { code: "IL", label: "Israel", flag: "🇮🇱" },
  { code: "TR", label: "Turkey", flag: "🇹🇷" },
  // Oceania
  { code: "AU", label: "Australia", flag: "🇦🇺" },
  { code: "NZ", label: "New Zealand", flag: "🇳🇿" },
] as const;

export const BOOK_CLUBS = [
  {
    id: "oprah",
    name: "Oprah's Book Club",
    curator: "Oprah Winfrey",
    emoji: "📖",
    count: 15,
  },
  {
    id: "billgates",
    name: "Bill Gates' Reading List",
    curator: "Bill Gates",
    emoji: "🧠",
    count: 15,
  },
  {
    id: "reese",
    name: "Reese's Book Club",
    curator: "Reese Witherspoon",
    emoji: "☀️",
    count: 15,
  },
  {
    id: "obama",
    name: "Obama's Reading List",
    curator: "Barack Obama",
    emoji: "📚",
    count: 15,
  },
  {
    id: "goodreads",
    name: "Goodreads Choice Awards",
    curator: "Goodreads Community",
    emoji: "⭐",
    count: 15,
  },
] as const;
