/**
 * BetweenPages Seed Script
 *
 * Populates Firestore with:
 * 1. Book data (from Gemini lists + Open Library covers)
 * 2. Country charts (Top 50 in India, USA, UK)
 * 3. Trending books
 * 4. Book clubs (Oprah, Bill Gates, NYT, Reese, Obama)
 * 5. Reviews (5 per book, spanning 1-5 stars, generated by Gemini)
 *
 * Run: npx tsx scripts/seed.ts
 */

import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ─── Firebase Admin init ───
// Uses the service account key for server-side Firestore writes.
// The seed script runs outside Next.js, so we can't use the client SDK.
import { readFileSync } from "fs";
import { resolve } from "path";

const serviceAccount = JSON.parse(
  readFileSync(resolve(__dirname, "../serviceAccountKey.json"), "utf-8")
);

const app = initializeApp({
  credential: cert(serviceAccount),
  projectId: "betweenpages-a658a",
});
const db = getFirestore(app);

// ─── Gemini init ───
const genAI = new GoogleGenerativeAI(
  process.env.GOOGLE_GENERATIVE_AI_API_KEY || ""
);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

// ─── Open Library helper ───
async function searchOpenLibrary(title: string, author: string) {
  try {
    const query = encodeURIComponent(`${title} ${author}`);
    const res = await fetch(
      `https://openlibrary.org/search.json?q=${query}&limit=1&fields=key,title,author_name,cover_i,number_of_pages_median,first_publish_year,isbn,subject`
    );
    if (!res.ok) return null;
    const data = await res.json();
    const doc = data.docs?.[0];
    if (!doc) return null;
    const coverId = doc.cover_i || null;
    return {
      coverUrl: coverId ? `https://covers.openlibrary.org/b/id/${coverId}-M.jpg` : null,
      openLibraryKey: doc.key || null,
      pageCount: doc.number_of_pages_median || null,
      publishedDate: doc.first_publish_year ? String(doc.first_publish_year) : null,
      isbn: doc.isbn?.[0] || null,
      subjects: (doc.subject || []).slice(0, 5),
    };
  } catch {
    return null;
  }
}

// ─── Gemini prompt helper ───
async function askGemini(prompt: string): Promise<string> {
  const result = await model.generateContent(prompt);
  return result.response.text();
}

function parseJsonFromGemini(text: string): unknown {
  // Strip markdown code fences if present
  const cleaned = text.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
  return JSON.parse(cleaned);
}

// ─── Rate limiter (polite 1 req/sec for Open Library) ───
function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ─── Types ───
type GeminiBook = {
  title: string;
  author: string;
  genre: string;
  language: string;
};

type GeminiReview = {
  rating: number;
  headline: string;
  body: string;
  reviewerName: string;
  reviewerPreference: string;
};

// ─── Step 1: Generate book lists via Gemini ───
async function generateBookList(prompt: string): Promise<GeminiBook[]> {
  const fullPrompt = `${prompt}

Return ONLY a JSON array with no other text. Each object must have:
- "title": string (exact book title)
- "author": string (author's full name)
- "genre": string (primary genre)
- "language": string (original language, e.g., "English", "Hindi")

Example: [{"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Literary Fiction", "language": "English"}]`;

  const text = await askGemini(fullPrompt);
  const books = parseJsonFromGemini(text) as GeminiBook[];
  console.log(`  → Generated ${books.length} books`);
  return books;
}

// ─── Step 2: Generate reviews via Gemini ───
async function generateReviews(
  title: string,
  author: string
): Promise<GeminiReview[]> {
  const prompt = `Generate 5 representative reader reviews for "${title}" by ${author}.
The reviews should span the full rating spectrum (one each of 1-star through 5-star).
For each review, explain WHY the reader felt that way. Include the reader's preferred genre to give context for their perspective.

Return ONLY a JSON array. Each object must have:
- "rating": number (1-5)
- "headline": string (one-line summary in quotes, max 10 words)
- "body": string (2-3 sentences explaining why this rating)
- "reviewerName": string (realistic first name + last initial)
- "reviewerPreference": string (their favorite genre, e.g., "Literary Fiction Fan", "Sci-Fi Reader")`;

  const text = await askGemini(prompt);
  return parseJsonFromGemini(text) as GeminiReview[];
}

// ─── Step 3: Enrich with Open Library + save to Firestore ───
async function enrichAndSaveBook(book: GeminiBook): Promise<string | null> {
  // Create a deterministic ID from title
  const bookId = book.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);

  // Check if already exists
  const existing = await db.collection("books").doc(bookId).get();
  if (existing.exists) {
    console.log(`  ⏭ Skipping "${book.title}" (already exists)`);
    return bookId;
  }

  // Fetch from Open Library
  const olData = await searchOpenLibrary(book.title, book.author);
  await sleep(500); // polite rate limiting

  const bookDoc = {
    id: bookId,
    title: book.title,
    author: book.author,
    coverUrl: olData?.coverUrl || null,
    description: "", // fetched on-demand from Open Library when user clicks
    categories: olData?.subjects || [book.genre],
    language: book.language,
    pageCount: olData?.pageCount || null,
    publishedDate: olData?.publishedDate || null,
    isbn: olData?.isbn || null,
    openLibraryKey: olData?.openLibraryKey || null,
    cachedAt: Date.now(),
  };

  await db.collection("books").doc(bookId).set(bookDoc);
  console.log(`  ✓ Saved "${book.title}" (cover: ${bookDoc.coverUrl ? "yes" : "no"})`);

  return bookId;
}

async function saveReviews(bookId: string, title: string, author: string) {
  try {
    const reviews = await generateReviews(title, author);
    const batch = db.batch();

    for (const review of reviews) {
      const reviewId = `seeded-${review.rating}`;
      const ref = db.collection("books").doc(bookId).collection("reviews").doc(reviewId);
      batch.set(ref, {
        ...review,
        id: reviewId,
        source: "seeded",
        createdAt: Date.now(),
      });
    }

    await batch.commit();
    console.log(`  ✓ Saved 5 reviews for "${title}"`);
  } catch (err) {
    console.error(`  ✗ Failed reviews for "${title}":`, err);
  }
}

// ─── Step 4: Create charts ───
async function createChart(
  id: string,
  name: string,
  type: string,
  bookIds: string[],
  country?: string
) {
  await db
    .collection("charts")
    .doc(id)
    .set({
      id,
      name,
      type,
      country: country || null,
      bookIds,
      updatedAt: Date.now(),
    });
  console.log(`✓ Chart "${name}" (${bookIds.length} books)`);
}

// ─── Step 5: Create book clubs ───
async function createBookClub(
  id: string,
  name: string,
  curator: string,
  description: string,
  avatarEmoji: string,
  bookIds: string[]
) {
  await db.collection("bookclubs").doc(id).set({
    id,
    name,
    curator,
    description,
    avatarEmoji,
    bookIds,
    updatedAt: Date.now(),
  });
  console.log(`✓ Book Club "${name}" (${bookIds.length} books)`);
}

// ═══════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════
async function main() {
  console.log("\n🌿 BetweenPages Seed Script\n");
  console.log("═".repeat(50));

  // ── Country charts ──
  console.log("\n📊 Generating country charts...\n");

  const indiaBooks = await generateBookList(
    "List the 20 most popular and widely-read books in India across all genres. Include both English and Hindi language books. Mix classic and contemporary."
  );

  const usaBooks = await generateBookList(
    "List the 20 most popular and widely-read books in the United States in 2024-2025. Include fiction and non-fiction bestsellers."
  );

  const ukBooks = await generateBookList(
    "List the 20 most popular and widely-read books in the United Kingdom in 2024-2025. Include fiction and non-fiction."
  );

  // ── Trending ──
  console.log("\n🔥 Generating trending books...\n");

  const trendingBooks = await generateBookList(
    "List 15 books that are currently trending worldwide in 2025. Include viral BookTok picks, award winners, and buzzy new releases."
  );

  // ── Book clubs ──
  console.log("\n📚 Generating book club lists...\n");

  const oprahBooks = await generateBookList(
    "List 15 books from Oprah's Book Club. Include recent and classic picks."
  );

  const gatesBooks = await generateBookList(
    "List 15 books that Bill Gates has recommended on his blog or GatesNotes."
  );

  const reeseBooks = await generateBookList(
    "List 15 books from Reese Witherspoon's Book Club (Reese's Book Club x Hello Sunshine)."
  );

  const obamaBooks = await generateBookList(
    "List 15 books from Barack Obama's annual reading lists and recommendations."
  );

  const goodreadsBooks = await generateBookList(
    "List 15 Goodreads Choice Awards winners from the last 5 years across different categories."
  );

  // ── Enrich all books ──
  console.log("\n📖 Enriching books with Open Library data...\n");

  // Deduplicate across all lists
  const allBooks = [
    ...indiaBooks,
    ...usaBooks,
    ...ukBooks,
    ...trendingBooks,
    ...oprahBooks,
    ...gatesBooks,
    ...reeseBooks,
    ...obamaBooks,
    ...goodreadsBooks,
  ];

  const seen = new Set<string>();
  const uniqueBooks: GeminiBook[] = [];
  for (const book of allBooks) {
    const key = `${book.title}::${book.author}`.toLowerCase();
    if (!seen.has(key)) {
      seen.add(key);
      uniqueBooks.push(book);
    }
  }

  console.log(`Total unique books: ${uniqueBooks.length}\n`);

  // Save books to Firestore
  const bookIdMap = new Map<string, string>(); // "title::author" → bookId

  for (const book of uniqueBooks) {
    const bookId = await enrichAndSaveBook(book);
    if (bookId) {
      bookIdMap.set(`${book.title}::${book.author}`.toLowerCase(), bookId);
    }
  }

  // ── Helper to get bookIds from a list ──
  function getIds(books: GeminiBook[]): string[] {
    return books
      .map((b) => bookIdMap.get(`${b.title}::${b.author}`.toLowerCase()))
      .filter((id): id is string => !!id);
  }

  // ── Save charts ──
  console.log("\n📊 Saving charts...\n");

  await createChart("top-india", "Top in India", "country", getIds(indiaBooks), "IN");
  await createChart("top-usa", "Top in United States", "country", getIds(usaBooks), "US");
  await createChart("top-uk", "Top in United Kingdom", "country", getIds(ukBooks), "GB");
  await createChart("trending", "Trending Now", "trending", getIds(trendingBooks));

  // ── Save book clubs ──
  console.log("\n📚 Saving book clubs...\n");

  await createBookClub(
    "oprah", "Oprah's Book Club", "Oprah Winfrey",
    "Oprah's curated picks spanning literary fiction, memoirs, and powerful stories.",
    "📖", getIds(oprahBooks)
  );
  await createBookClub(
    "billgates", "Bill Gates' Reading List", "Bill Gates",
    "Recommended by Bill Gates on GatesNotes — science, business, and big ideas.",
    "🧠", getIds(gatesBooks)
  );
  await createBookClub(
    "reese", "Reese's Book Club", "Reese Witherspoon",
    "Hello Sunshine picks — stories with strong women at the center.",
    "☀️", getIds(reeseBooks)
  );
  await createBookClub(
    "obama", "Obama's Reading List", "Barack Obama",
    "Annual reading recommendations from the 44th President.",
    "📚", getIds(obamaBooks)
  );
  await createBookClub(
    "goodreads", "Goodreads Choice Awards", "Goodreads Community",
    "Winners voted by millions of Goodreads readers.",
    "⭐", getIds(goodreadsBooks)
  );

  // ── Generate reviews for a subset ──
  console.log("\n💬 Generating reviews (first 30 books)...\n");

  const booksForReviews = uniqueBooks.slice(0, 30);
  for (const book of booksForReviews) {
    const bookId = bookIdMap.get(`${book.title}::${book.author}`.toLowerCase());
    if (bookId) {
      await saveReviews(bookId, book.title, book.author);
      await sleep(1000); // rate limit Gemini calls
    }
  }

  // ── Done ──
  console.log("\n" + "═".repeat(50));
  console.log(`\n🌿 Seed complete!`);
  console.log(`   Books: ${bookIdMap.size}`);
  console.log(`   Charts: 4`);
  console.log(`   Book Clubs: 5`);
  console.log(`   Reviews: ~${booksForReviews.length * 5}`);
  console.log();

  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
